version: "3"
services:
  influx:
    container_name: influx
    image: influxdb:2.7.6-alpine
    ports:
      - 8086:8086
    networks:
      - back
    volumes:
      - ./influxDB/data:/var/lib/influxdb2
      - ./influxDB/config:/etc/influxdb2

  rabbitmq:
    image: rabbitmq:3.13.4-management
    ports:
      - 5672:5672  # RabbitMQ default port
      - 15672:15672  # RabbitMQ management UI port
    networks:
    - worker
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq  # Persist data on the host machine
      - ./rabbitmq/init.sh:/usr/local/bin/init.sh
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_MANAGEMENT_LOAD_DEFINITIONS=/etc/rabbitmq/definitions.json
      - RABBIT_USER=sensor
      - RABBIT_PASS=TOKEN
      - RABBIT_PID_FILE=/var/lib/rabbitmq/mnesia/rabbitmq
    command: 
    - "/usr/local/bin/init.sh"

networks:
  back:
  worker: